package com.haulmont.testtask.entities;

import com.haulmont.testtask.interfaces.IHospitalUser;
import com.vaadin.annotations.AutoGenerated;

import javax.persistence.*;

@Entity
public class Patient implements IHospitalUser {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id", unique=true, nullable = false)
    private Long id;

    @Column (name = "name")
    private String name;

    @Column (name = "surname")
    private String surname;

    @Column (name = "patronymic")
    private String patronymic;

    @Column (name = "telephone")
    private String telephone;

    public Patient(){}

    public Patient(String name, String surname, String patronymic, String telephone){
        this.name = name;
        this.surname = surname;
        this.patronymic = patronymic;
        this.telephone = telephone;
    }

    public Long getId() { return id; }

    public String getName() { return name; }

    public String getSurname() {
        return surname;
    }

    public String getPatronymic() {
        return patronymic;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public void setName(String name) { this.name = name; }

    public void setSurname(String surname) { this.surname = surname; }

    public void setPatronymic(String patronymic) {
        this.patronymic = patronymic;
    }
}
