package com.haulmont.testtask.entities;

import com.vaadin.annotations.AutoGenerated;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQuery;

@Entity
public class Patient {

    @Id
    @AutoGenerated
    private Long id;

    private String name;
    private String surname;
    private String patronymic;
    private String telephone;

    public Patient(){}

    public Patient(String name, String surname, String patronymic, String telephone){
        this.name = name;
        this.surname = surname;
        this.patronymic = patronymic;
        this.telephone = telephone;
    }

    public Long getId() { return id; }

    public String getName() { return name; }

    public String getSurname() {
        return surname;
    }

    public String getPatronymic() {
        return patronymic;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public void setName(String name) { this.name = name; }

    public void setSurname(String surname) { this.surname = surname; }

    public void setPatronymic(String patronymic) {
        this.patronymic = patronymic;
    }
}
