package com.haulmont.testtask.entities;

import com.vaadin.annotations.AutoGenerated;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;
import java.sql.Date;

@Entity
public class Recipe {
    @Id
    @AutoGenerated
    private Long id;

    private String description;
    @NotNull
    private Long patientId;
    @NotNull
    private Long doctorId;
    private Date dateRecipeCreation;
    private int validityDays;
    private String priority;

    public Recipe(){}

    public Recipe(String description, Long patientId, Long doctorId, Date dateRecipeCreation, int validityDays, String priority){
        this.description = description;
        this.patientId = patientId;
        this.dateRecipeCreation = dateRecipeCreation;
        this.validityDays = validityDays;
        this.priority = priority;
    }


    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getPatientId() {
        return patientId;
    }

    public void setPatientId(Long patientId) {
        this.patientId = patientId;
    }

    public Long getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    public Date getDateRecipeCreation() {
        return dateRecipeCreation;
    }

    public void setDateRecipeCreation(Date dateRecipeCreation) {
        this.dateRecipeCreation = dateRecipeCreation;
    }

    public int getValidityDays() {
        return validityDays;
    }

    public void setValidityDays(int validityDays) {
        this.validityDays = validityDays;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }
}
