package com.haulmont.testtask.entities;

import com.haulmont.testtask.interfaces.IHospitalUser;
import com.vaadin.annotations.AutoGenerated;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Date;

@Entity
@Table(name = "Recipe")
public class Recipe {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id", unique=true, nullable = false)
    private Long id;

    @Column (name = "description")
    private String description;

    @Column (name = "patientId")
    private Long patientId;

    @Column (name = "doctorId")
    private Long doctorId;

    @Column (name = "dateRecipeCreation")
    private Date dateRecipeCreation;

    @Column (name = "validityDays")
    private int validityDays;

    @Column (name = "priority")
    private String priority;

    public Recipe() {
    }

    public Recipe(String description, Long patientId, Long doctorId, Date dateRecipeCreation, int validityDays, String priority) {
        this.description = description;
        this.patientId = patientId;
        this.doctorId = doctorId;
        this.dateRecipeCreation = dateRecipeCreation;
        this.validityDays = validityDays;
        this.priority = priority;
    }

    public Long getId() { return id; }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getPatientId() {
        return patientId;
    }

    public void setPatientId(Long patientId) {
        this.patientId = patientId;
    }

    public Long getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    public Date getDateRecipeCreation() {
        return dateRecipeCreation;
    }

    public void setDateRecipeCreation(Date dateRecipeCreation) {
        this.dateRecipeCreation = dateRecipeCreation;
    }

    public int getValidityDays() {
        return validityDays;
    }

    public void setValidityDays(int validityDays) {
        this.validityDays = validityDays;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }
}
